---
title: ''
author: "Yaoru Yi"
date: "2 May 2016"
output: html_document
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(RColorBrewer)
library(plotly)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

data2 <- read.csv('2015_0101_0131.csv')

### calculate the response (days)
data2$Created.Date <- as.POSIXct(data2$Created.Date, format = '%m/%d/%Y %I:%M:%S %p')
data2$Closed.Date <- as.POSIXct(data2$Closed.Date, format = '%m/%d/%Y %I:%M:%S %p')
data2$response <- floor(as.numeric(difftime(data2$Closed.Date,data2$Created.Date, units="days")))

### remove Nas in response column 
data2 <- data2[!is.na(data2$response),]

### subset days 
Jan01_15<- data2[grepl('01-01',data2$Created.Date),]
Jan02_15<- data2[grepl('01-02',data2$Created.Date),]
Jan03_15<- data2[grepl('01-03',data2$Created.Date),]
Jan04_15<- data2[grepl('01-04',data2$Created.Date),]
Jan05_15<- data2[grepl('01-05',data2$Created.Date),]
Jan06_15<- data2[grepl('01-06',data2$Created.Date),]
Jan07_15<- data2[grepl('01-07',data2$Created.Date),]
Jan08_15<- data2[grepl('01-08',data2$Created.Date),]
Jan09_15 <-data2[grepl('01-09',data2$Created.Date),]
Jan10_15 <-data2[grepl('01-10', data2$Created.Date),]
Jan11_15 <-data2[grepl('01-11', data2$Created.Date),]
Jan12_15 <-data2[grepl('01-12', data2$Created.Date),]
Jan13_15 <-data2[grepl('01-13', data2$Created.Date),]
Jan14_15 <-data2[grepl('01-14', data2$Created.Date),]
Jan15_15 <-data2[grepl('01-15', data2$Created.Date),]
Jan16_15 <-data2[grepl('01-16', data2$Created.Date),]
Jan17_15 <-data2[grepl('01-17', data2$Created.Date),]
Jan18_15 <-data2[grepl('01-18', data2$Created.Date),]
Jan19_15 <-data2[grepl('01-19', data2$Created.Date),]
Jan20_15 <-data2[grepl('01-20', data2$Created.Date),]
Jan21_15 <-data2[grepl('01-21', data2$Created.Date),]
Jan22_15 <-data2[grepl('01-22', data2$Created.Date),]
Jan23_15 <-data2[grepl('01-23', data2$Created.Date),]
Jan24_15 <-data2[grepl('01-24', data2$Created.Date),]
Jan25_15 <-data2[grepl('01-25', data2$Created.Date),]
Jan26_15 <-data2[grepl('01-26', data2$Created.Date),]
Jan27_15 <-data2[grepl('01-27', data2$Created.Date),]
Jan28_15 <-data2[grepl('01-28', data2$Created.Date),]
Jan29_15 <-data2[grepl('01-29', data2$Created.Date),]
Jan30_15 <-data2[grepl('01-30', data2$Created.Date),]
Jan31_15 <-data2[grepl('01-31', data2$Created.Date),]

JanDates <- c('2015-01-01','2015-01-02','2015-01-03','2015-01-04',
                   '2015-01-05','2015-01-06','2015-01-07','2015-01-08',
                   '2015-01-09','2015-01-10','2015-01-11','2015-01-12',
                   '2015-01-13','2015-01-14','2015-01-15','2015-01-16',
                   '2015-01-17','2015-01-18','2015-01-19','2015-01-20',
                   '2015-01-21','2015-01-22','2015-01-23','2015-01-24',
                   '2015-01-25','2015-01-26','2015-01-27','2015-01-28',
                   '2015-01-29','2015-01-30','2015-01-31')
borough_union <-c('BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND')
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
### Complaint Information Extraction function
ComplaintInfo <- function(complaint, complaintType, complaintCount, complaintBorough){
  complaint[[1]] <- Jan01_15[Jan01_15$Complaint.Type==complaintType,]
  complaint[[2]] <- Jan02_15[Jan02_15$Complaint.Type==complaintType,]
  complaint[[3]] <- Jan03_15[Jan03_15$Complaint.Type==complaintType,]
  complaint[[4]] <- Jan04_15[Jan04_15$Complaint.Type==complaintType,]
  complaint[[5]] <- Jan05_15[Jan05_15$Complaint.Type==complaintType,]
  complaint[[6]] <- Jan06_15[Jan06_15$Complaint.Type==complaintType,]
  complaint[[7]] <- Jan07_15[Jan07_15$Complaint.Type==complaintType,]
  complaint[[8]] <- Jan08_15[Jan08_15$Complaint.Type==complaintType,]
  complaint[[9]] <- Jan09_15[Jan09_15$Complaint.Type==complaintType,]
  complaint[[10]] <- Jan10_15[Jan10_15$Complaint.Type==complaintType,]
  complaint[[11]] <- Jan11_15[Jan11_15$Complaint.Type==complaintType,]
  complaint[[12]] <- Jan12_15[Jan12_15$Complaint.Type==complaintType,]
  complaint[[13]] <- Jan13_15[Jan13_15$Complaint.Type==complaintType,]
  complaint[[14]] <- Jan14_15[Jan14_15$Complaint.Type==complaintType,]
  complaint[[15]] <- Jan15_15[Jan15_15$Complaint.Type==complaintType,]
  complaint[[16]] <- Jan16_15[Jan16_15$Complaint.Type==complaintType,]
  complaint[[17]] <- Jan17_15[Jan17_15$Complaint.Type==complaintType,]
  complaint[[18]] <- Jan18_15[Jan18_15$Complaint.Type==complaintType,]
  complaint[[19]] <- Jan19_15[Jan19_15$Complaint.Type==complaintType,]
  complaint[[20]] <- Jan20_15[Jan20_15$Complaint.Type==complaintType,]
  complaint[[21]] <- Jan21_15[Jan21_15$Complaint.Type==complaintType,]
  complaint[[22]] <- Jan22_15[Jan22_15$Complaint.Type==complaintType,]
  complaint[[23]] <- Jan23_15[Jan23_15$Complaint.Type==complaintType,]
  complaint[[24]] <- Jan24_15[Jan24_15$Complaint.Type==complaintType,]
  complaint[[25]] <- Jan25_15[Jan25_15$Complaint.Type==complaintType,]
  complaint[[26]] <- Jan26_15[Jan26_15$Complaint.Type==complaintType,]
  complaint[[27]] <- Jan27_15[Jan27_15$Complaint.Type==complaintType,]
  complaint[[28]] <- Jan28_15[Jan28_15$Complaint.Type==complaintType,]
  complaint[[29]] <- Jan29_15[Jan29_15$Complaint.Type==complaintType,]
  complaint[[30]] <- Jan30_15[Jan30_15$Complaint.Type==complaintType,]
  complaint[[31]] <- Jan31_15[Jan31_15$Complaint.Type==complaintType,]
  
  for (i in 1:31){ 
    for (j in 1:5){   # loop through zips of a particular date
      borough_temp = borough_union[j] 
      complaintCount[i,borough_temp] = round(mean(complaint           [[i]][complaint[[i]]$Borough==borough_temp,]$response),2)
    }  
  }
  
  #### cols are date, response time, borough   (115 by 3) 
  for (i in 1:31){
    for (j in 1:5){
      complaintBorough[(i-1)*5+j, 1] = rownames(complaintCount)[i]
      complaintBorough[(i-1)*5+j, 2] = complaintCount[i,j]
      complaintBorough[(i-1)*5+j, 3] = colnames(complaintCount)[j]
    }
  }
  
  complaintCount <- data.frame(complaintCount)
  complaintBorough <- data.frame(complaintBorough)
  
  return (list(complaintCount, complaintBorough))
}


```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#### Some complaints by HPD 

### HEAT/HOT WATER 
Heat <- vector(mode='list', length=31)
names(Heat) <- JanDates
Heat_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(Heat_count) <- borough_union
rownames(Heat_count) <- JanDates
Heat_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(Heat_borough) <- c('date', 'response', 'borough')
Heat_result <- ComplaintInfo(Heat, 'HEAT/HOT WATER', Heat_count, Heat_borough)
Heat_count <- data.frame(Heat_result[1])
Heat_borough <- data.frame(Heat_result[2])

### Unsanitary Condition 
Unsanitary <-vector(mode='list', length=31)
names(Unsanitary) <- JanDates
Unsanitary_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(Unsanitary_count) <- borough_union
rownames(Unsanitary_count) <- JanDates
Unsanitary_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(Unsanitary_borough) <- c('date', 'response', 'borough')
Unsanitary_result <- ComplaintInfo(Unsanitary, 'UNSANITARY CONDITION', Unsanitary_count, Unsanitary_borough)
Unsanitary_count <- data.frame(Unsanitary_result[1])
Unsanitary_borough <- data.frame(Unsanitary_result[2])

### PAINT/PLASTER 
Paint <- vector(mode='list', length=31)
names(Paint) <- JanDates
Paint_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(Paint_count) <- borough_union
rownames(Paint_count) <- JanDates
Paint_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(Paint_borough) <- c('date', 'response', 'borough')
Paint_result <- ComplaintInfo(Paint, 'PAINT/PLASTER', Paint_count, Paint_borough)
Paint_count <- data.frame(Paint_result[1])
Paint_borough <- data.frame(Paint_result[2])

### PLUMBING 
Plumbing <- vector(mode='list', length=31)
names(Plumbing) <- JanDates
Plumbing_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(Plumbing_count) <- borough_union
rownames(Plumbing_count) <- JanDates
Plumbing_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(Plumbing_borough) <- c('date', 'response', 'borough')
Plumbing_result <- ComplaintInfo(Plumbing, 'PLUMBING', Plumbing_count, Plumbing_borough)
Plumbing_count <- data.frame(Plumbing_result[1])
Plumbing_borough <- data.frame(Plumbing_result[2])

### DOOR/WINDOW
DoorWindow <- vector(mode='list', length=31)
names(DoorWindow) <- JanDates
DoorWindow_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(DoorWindow_count) <- borough_union
rownames(DoorWindow_count) <- JanDates
DoorWindow_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(DoorWindow_borough) <- c('date', 'response', 'borough')
DoorWindow_result <- ComplaintInfo(DoorWindow, 'PLUMBING', DoorWindow_count, DoorWindow_borough)
DoorWindow_count <- data.frame(DoorWindow_result[1])
DoorWindow_borough <- data.frame(DoorWindow_result[2])


```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#### Some complaints by DOT

### Street Condition 
StreetCond <- vector(mode='list', length=31)
names(StreetCond) <- JanDates
StreetCond_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(StreetCond_count) <- borough_union
rownames(StreetCond_count) <- JanDates
StreetCond_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(StreetCond_borough) <- c('date', 'response', 'borough')
StreetCond_result <- ComplaintInfo(StreetCond, 'Street Condition', StreetCond_count, StreetCond_borough)
StreetCond_count <- data.frame(StreetCond_result[1])
StreetCond_borough <- data.frame(StreetCond_result[2])

### Street Light Condition 
StreetLight <- vector(mode='list', length=31)
names(StreetLight) <- JanDates
StreetLight_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(StreetLight_count) <- borough_union
rownames(StreetLight_count) <- JanDates
StreetLight_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(StreetLight_borough) <- c('date', 'response', 'borough')
StreetLight_result <- ComplaintInfo(StreetLight, 'Street Light Condition', StreetLight_count, StreetLight_borough)
StreetLight_count <- data.frame(StreetLight_result[1])
StreetLight_borough <- data.frame(StreetLight_result[2])

### Traffic Signal Condition
TrafficSig <- vector(mode='list', length=31)
names(TrafficSig) <- JanDates
TrafficSig_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(TrafficSig_count) <- borough_union
rownames(TrafficSig_count) <- JanDates
TrafficSig_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(TrafficSig_borough) <- c('date', 'response', 'borough')
TrafficSig_result <- ComplaintInfo(TrafficSig, 'Traffic Signal Condition', TrafficSig_count, TrafficSig_borough)
TrafficSig_count <- data.frame(TrafficSig_result[1])
TrafficSig_borough <- data.frame(TrafficSig_result[2])

### Broken Muni Meter
MuniMeter <- vector(mode='list', length=31)
names(MuniMeter) <- JanDates
MuniMeter_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(MuniMeter_count) <- borough_union
rownames(MuniMeter_count) <- JanDates
MuniMeter_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(MuniMeter_borough) <- c('date', 'response', 'borough')
MuniMeter_result <- ComplaintInfo(MuniMeter, 'Broken Muni Meter', MuniMeter_count, MuniMeter_borough)
MuniMeter_count <- data.frame(MuniMeter_result[1])
MuniMeter_borough <- data.frame(MuniMeter_result[2])

### Highway Condition
Highway <- vector(mode='list', length=31)
names(Highway) <- JanDates
Highway_count <- matrix(NA, ncol=length(borough_union), nrow=31)
colnames(Highway_count) <- borough_union
rownames(Highway_count) <- JanDates
Highway_borough <- matrix(NA, ncol=3, nrow= 155)
colnames(Highway_borough) <- c('date', 'response', 'borough')
Highway_result <- ComplaintInfo(Highway, 'Highway Condition', Highway_count, Highway_borough)
Highway_count <- data.frame(Highway_result[1])
Highway_borough <- data.frame(Highway_result[2])


```
> ### Agency's efficiency of closing different types of complaints 
####(Jan 1st - Jan 15th 2015)

> #### HPD in Manhattan Borough 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
### From Jan 1st till 31st, HPD got reported of 49039 number of Heat/Hot Water complaints,
### 5945 number of Unsanitary Condition complaints, 5777 Paint/Plaster complaints,
### 5340 Plumbing, 3834 Door/Window

Heat_tmp = Heat_borough[Heat_borough$borough=='MANHATTAN',]
Unsanitary_tmp = Unsanitary_borough[Unsanitary_borough$borough=='MANHATTAN',]
Paint_tmp = Paint_borough[Paint_borough$borough=='MANHATTAN',]
Plumbing_tmp = Plumbing_borough[Plumbing_borough$borough=='MANHATTAN',]
DoorWindow_tmp = DoorWindow_borough[DoorWindow_borough$borough=='MANHATTAN',]

HPD_complaint_object = list(Heat_tmp, Unsanitary_tmp, Paint_tmp, Plumbing_tmp, DoorWindow_tmp)
HPD_complaint_name = c('HEAT/HOT WATER', 'Unsanitary Condition', 'PAINT/PLASTER', 'PLUMBING',
                       'DOOR/WINDOW')

HPD_manhattan <- matrix(NA, ncol=3, nrow= 155)  # 31 days, 5 types of complaints
colnames(HPD_manhattan) <- c('date', 'response', 'complaint')
for (i in 1:31){
  for (j in 1:5){
    HPD_manhattan[(i-1)*5+j, 1] = JanDates[i]
    HPD_manhattan[(i-1)*5+j, 2] = as.numeric(HPD_complaint_object[[j]]$response[i])
    HPD_manhattan[(i-1)*5+j, 3] = HPD_complaint_name[j]  
  }
}

HPD_manhattan <- data.frame(HPD_manhattan)

plot_ly(data = HPD_manhattan[1:75,], x = date, y = response, type='bar', #mode = "markers",
        color =complaint)%>%
  layout(title="Average days for HPD to close different complaints (reported in Manhattan)")

```


> #### DOT in Manhattan Borough 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
### From Jan 1st till 31st, DOT got reported of 7104 Street Condition complaints,
### 6982 Street Light Condition complaints, 4439 Traffic Signal Condition complaints,
### 1677 Broken Muni Meter, 371 Highway Condition.

StreetCond_tmp = StreetCond_borough[StreetCond_borough$borough=='MANHATTAN',]
StreetLight_tmp = StreetLight_borough[StreetLight_borough$borough=='MANHATTAN',]
TrafficSig_tmp = TrafficSig_borough[TrafficSig_borough$borough=='MANHATTAN',]
MuniMeter_tmp = MuniMeter_borough[MuniMeter_borough$borough=='MANHATTAN',]
Highway_tmp = Highway_borough[Highway_borough$borough=='MANHATTAN',]

DOT_complaint_object = list(StreetCond_tmp, StreetLight_tmp, TrafficSig_tmp, MuniMeter_tmp, Highway_tmp)
DOT_complaint_name = c('Street Condition', 'Street Light Condition', 'Traffic Signal Condition', 'Broken Muni Meter', 'Highway Condition')

DOT_manhattan <- matrix(NA, ncol=3, nrow= 155)  # 31 days, 5 types of complaints
colnames(DOT_manhattan) <- c('date', 'response', 'complaint')
for (i in 1:31){
  for (j in 1:5){
    DOT_manhattan[(i-1)*5+j, 1] = JanDates[i]
    DOT_manhattan[(i-1)*5+j, 2] = as.numeric(DOT_complaint_object[[j]]$response[i])
    DOT_manhattan[(i-1)*5+j, 3] = DOT_complaint_name[j]  
  }
}

DOT_manhattan <- data.frame(DOT_manhattan)

plot_ly(data = DOT_manhattan[1:75,], x = date, y = response, type='bar', #mode = "markers",
        color =complaint)%>%
  layout(title="Average days for DOT to close different complaints (reported in Manhattan)")

```
