---
title: "Data Parse"
author: "Team"
date: "February 13, 2016"
output: html_document
---
```{r}
library(dplyr)
library(ggplot2)
library(knitr)
#install.packages("devtools")
#devtools::install_github("twitter/AnomalyDetection")

library(AnomalyDetection)
library(googleVis)
op <- options(gvis.plot.tag='chart')

setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/Final_Project/Edav-P4")

#df = read.csv("311_full.csv")
#saveRDS(df,"full_filtered2.rds")
#Filter for noises
#Noise_filter = grepl("Noise",df$Complaint.Type)
#df.noise = df[Noise_filter,]
#setwd("/Users/bobminnich/Documents/Columbia/Courses/Applied_Data_Science/")
#df = read.csv("311_1 Year.csv")
#df = read.csv("311_Full_Filtered.csv")
#df = df[1:(nrow(df)/8),]

df = readRDS("full_filtered2.rds")

#setwd("/Users/bobminnich/Documents/Columbia/Courses/Applied_Data_Science/project2-group3/doc")

```

Parse Dates into columns
```{r}
#date_clean <- data.frame(do.call('rbind', strsplit(as.character(df$Created.Date),"\\s+")))
#date_clean$X1 = as.Date(as.character(date_clean$X1),format ="%m/%d/%Y")
#colnames(date_clean) = c("Date", "Time", "AM/PM")
#df = cbind(df,date_clean)


#date_clean <- data.frame(do.call('rbind', strsplit(as.character(df$Created.Date),"\\s+")))
#month_clean <- data.frame(do.call('rbind', strsplit(as.character(Complaints_total$Date),"-")))


```

```{r}
colnames(df) = c("Date","Complaint.Type")
complaint_list = unique(df$Complaint.Type)
df$Date = as.Date(as.character(df$Date),format ="%m/%d/%Y")
df$Date = as.POSIXct(df$Date)
df$Day = strftime(df$Date, "%d")
df$Month = strftime(df$Date, "%m")
df$Year = strftime(df$Date, "%Y")

df_2 = df[, c("Complaint.Type","Date")]
df2 = group_by(df_2,Date,Complaint.Type)
df3 = summarise(df2, count = n())
complaint_list2 = complaint_list[1:3]


anom_df = data.frame()
for(i in complaint_list){
  df4 = filter(df3, Complaint.Type == i)
  df5 = df4[,c("Date","count")]
  if(nrow(df5)>50){
    res = AnomalyDetectionTs(df5, max_anoms=0.02, direction='both', plot=FALSE,piecewise_median_period_weeks = 3)
  
    if(nrow(res$anoms) > 0){
      test_df = data.frame(res$anoms)
      test_df$Complaint = i
      anom_df = rbind(anom_df,test_df)
    }
  }
}
anom_df$timestamp = as.POSIXct(anom_df$timestamp)


```


```{r}
Complaint_Lookup = "HEAT/HOT WATER"
plot_time = filter(df3,Complaint.Type == Complaint_Lookup )
anom_df$timestamp = as.POSIXct(anom_df$timestamp)
plot_anom = filter(anom_df, Complaint == Complaint_Lookup)
ggplot(plot_time, aes(x=Date, y=count, colour = "blue"))+
  geom_line() + 
  geom_point(data = plot_anom, aes(x = timestamp, y = anoms, colour = "red"))

```


```{r,results='asis',tidy=FALSE, echo=FALSE, fig.align='left'}
bubble = group_by(anom_df,Complaint)
bubble2 = summarise(bubble,sum(anoms))
colnames(bubble2) = c("Complaint", "Count")
bubble2$index = c(1:nrow(bubble2))
ggplot(bubble2, aes(x=index, y=log(Count), size=(Count), label=Complaint),guide=FALSE)+
    geom_point(aes(size = log(Count), colour = Count, alpha=.02)) 


```


```{r,results='asis',tidy=FALSE, echo=FALSE, fig.align='left'}
bubble2$log = log(bubble2$Count)
Bubble <- gvisBubbleChart(bubble2, idvar = "Complaint", xvar = "index", 
                          yvar = "Count", 
                          colorvar = "Count", sizevar = "Count", 
                          options = list(colorAxis = "{colors: ['lightblue', 'blue']}", 
                          vAxis = "{title:'Mean Income'}", hAxis = "{title:'First Entry'}", 
                         width = 1000, height = 1000, bubble = "{textStyle:{color: 'none',fontName: 'Times-Roman', fontSize:9}}",           explorer = "{actions: ['dragToZoom', 'rightClickToReset'] }",
                         title = "Mean Income Bubble Chart"))

plot(Bubble)

```

```{r,results='asis',tidy=FALSE, echo=FALSE, fig.align='left'}
bubble2$log = log(bubble2$Count)
Bubble <- gvisBubbleChart(bubble2, idvar = "Complaint", xvar = "index", 
                          yvar = "log", 
                          colorvar = "log", sizevar = "log", 
                          options = list(colorAxis = "{colors: ['lightblue', 'blue']}", 
                          vAxis = "{title:'Mean Income'}", hAxis = "{title:'First Entry'}", 
                         width = 1000, height = 1000, bubble = "{textStyle:{color: 'none',fontName: 'Times-Roman', fontSize:9}}",           explorer = "{actions: ['dragToZoom', 'rightClickToReset'] }",
                         title = "Mean Income Bubble Chart"))

plot(Bubble)

```


```{r}

df2 = group_by(df,Date)
df3 = summarise(df2, count = n())
res = AnomalyDetectionTs(df3, max_anoms=0.02, direction='both', plot=TRUE,piecewise_median_period_weeks = 3)
beg = as.Date("2016-01-04")
end = as.Date("2016-01-05")
res$plot

res$anoms[order(res$anoms$anoms),]

ggplot(df3,aes(x = Date,y = count))+ 
  geom_line() +
  xlim(as.POSIXct("2013-01-20"),as.POSIXct("2013-01-24"))

count=  0
for(i in 1:nrow(df3)){
  if(df3$count[i] == 9033){
    count= count + 1
  }
}
print(count)
```



```{r}
df2 = group_by(df,Day,Month,Year)
df3 = summarise(df2, count = n())
df3$Date = paste(df3$Month,df3$Day,df3$Year,sep = "/")
df3$Date = as.Date(as.character(df3$Date),format ="%m/%d/%Y")
df3$Date = as.POSIXct(df3$Date)

res = AnomalyDetectionTs(df3, max_anoms=0.02, direction='both', plot=TRUE,piecewise_median_period_weeks = 3)
beg = as.Date("2016-01-04")
end = as.Date("2016-01-05")
res$plot

res$anoms[order(res$anoms$anoms),]

ggplot(df3,aes(x = Date,y = count))+ 
  geom_line() +
  xlim(as.POSIXct("2013-01-20"),as.POSIXct("2013-01-24"))

```



```{r}
df2 = group_by(filter(df,Year == 2015 & Month == "01" & Day == "07"),Day,Month,Year)
df3 = summarise(df2, count = n())
df3$Date = paste(df3$Month,df3$Day,df3$Year,sep = "/")
df3$Date = as.Date(as.character(df3$Date),format ="%m/%d/%Y")
df3$Date = as.POSIXct(df3$Date)

res = AnomalyDetectionTs(df3, max_anoms=0.02, direction='both', plot=TRUE,piecewise_median_period_weeks = 3)
beg = as.Date("2016-01-04")
end = as.Date("2016-01-05")
res$plot

res$anoms[order(res$anoms$anoms),]

```

```{r}
test = filter(df, Date > as.POSIXct("2015-01-06") & Date < as.POSIXct("2015-01-08"))
df2 = group_by(filter(test,Year == 2015 & Month == "01" & Day == "07"),Day,Month,Year)
df3 = summarise(df2, count = n())

test_df = read.csv("311_Jan_07_2015.csv")
```


```{r}
df_test = read.csv("test.csv")
colnames(df_test) = c("Date","Complaint.Type")

df_test$Date = as.Date(as.character(df_test$Date),format ="%m/%d/%Y")
df_test$Date = as.POSIXct(df_test$Date)
df_test$Day = strftime(df_test$Date, "%d")
df_test$Month = strftime(df_test$Date, "%m")
df_test$Year = strftime(df_test$Date, "%Y")
test = filter(test,Year == 2015 & Month == "01" & Day == "07")
df2 = group_by(,Day,Month,Year)
df3 = summarise(df2, count = n())

write.csv(test,"Jan_07_2015.csv")

```

