---
title: "Response Analysis"
output: html_document
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}
#data <- read.csv('Jan_08_2015.csv', header=T, na.strings=c("","NA"))
# remove Nas. 
#data <- data[-which(is.na(data$Closed.Date)),]

# change the timestamp 
#data$Created.Date <- as.POSIXct(data$Created.Date, format = '%m/%d/%Y %I:%M:%S %p')
#data$Closed.Date <- as.POSIXct(data$Closed.Date, format = '%m/%d/%Y %I:%M:%S %p')

# calculate the response (days)
#data$response <- floor(as.numeric(difftime(data$Closed.Date,data$Created.Date, units="days")))

# check how's the distribution of complaints 
# summary(data$Complaint.Type)
# (301 Door/Window  300 Paint/Plaster 240 Street Condition)
```
> ####   Top 5 types of complaints and the relating agencies: 

  Complaints Type         Total Count    Agency Type
------------------------ ------------- --------------
  Heat/Hot Water             5269           HPD 
  Street Light Condition     426            DOT
  Plumbing                   400            HPD
  Water System               330            DEP
  Unsanitary Condition       305            HPD 
------------------------- ------------- -------------

> #### Heat/Hot Water Complaints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
#install.packages("devtools")
#library(devtools)
#install_github('arilamstein/choroplethrZip@v1.5.0')  
library(choroplethr)
library(choroplethrZip)
data(df_pop_zip) 
#HPD <- data[data$Agency=='HPD',] 
#HPD_heat <- HPD[HPD$Complaint.Type=='HEAT/HOT WATER',]

# save(HPD_heat, file="HPD_heat.Rda")
# load("HPD_heat.Rda")

#zip_list_1 = unique(HPD_heat$Incident.Zip)
#zip_count_1 <- matrix(0, ncol=length(zip_list_1), nrow=1)
#colnames(zip_count_1) <- zip_list_1

#for (i in 1:length(zip_list_1)) {
#   temp = HPD_heat[HPD_heat$Incident.Zip == zip_list_1[i], ]
#   zip_count_1[1, as.character(zip_list_1[i])] = round(mean(temp$response),2)
# } 
#rm(temp)
#heat_response = data.frame(region = colnames(zip_count_1), value = #zip_count_1[,colnames(zip_count_1)])
#heat_response$region <- as.factor(heat_response$region)
#save(heat_response, file="heat_response.Rda")
load("heat_response.Rda")

nyc_fips <- c(36005, 36047, 36061, 36081, 36085)
zip_choropleth(heat_response, county_zoom=nyc_fips,
            title="Average time for HPD to close the heat/hot water claims",
            legend="Days")

#zip_min_1 <- matrix(0, ncol=length(zip_list_1), nrow=1)
#colnames(zip_min_1) <- zip_list_1

#for (i in 1:length(zip_list_1)) {
#   temp = HPD_heat[HPD_heat$Incident.Zip == zip_list_1[i], ]
#   zip_min_1[1, as.character(zip_list_1[i])] = min(temp$response)
# } 
#rm(temp)
#heat_response_min = data.frame(region = colnames(zip_min_1), value = #zip_min_1[,colnames(zip_min_1)])
#heat_response_min$region <- as.factor(heat_response_min$region)
#save(heat_response_min, file="heat_response_min.Rda")
load("heat_response_min.Rda")
zip_choropleth(heat_response_min, county_zoom=nyc_fips,
            title="Minimum time for HPD to close the heat/hot water claims",
            legend="Days")

#zip_max_1 <- matrix(0, ncol=length(zip_list_1), nrow=1)
#colnames(zip_max_1) <- zip_list_1

#for (i in 1:length(zip_list_1)) {
#   temp = HPD_heat[HPD_heat$Incident.Zip == zip_list_1[i], ]
#   zip_max_1[1, as.character(zip_list_1[i])] = max(temp$response)
# } 
#rm(temp)
#heat_response_max = data.frame(region = colnames(zip_max_1), value = zip_max_1[,colnames(zip_max_1)])
#heat_response_max$region <- as.factor(heat_response_max$region)
#save(heat_response_max, file="heat_response_max.Rda")
load("heat_response_max.Rda")
zip_choropleth(heat_response_max, county_zoom=nyc_fips,
            title="Maximum time for HPD to close the heat/hot water claims",
            legend="Days")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# zooming in a few Zips 
zipZoom <- function(df, zipcode, writetitle, writelegend){
  zip_choropleth(df,
                 zip_zoom = zipcode, 
                 title = writetitle,
                 legend = writelegend)
}

#{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=5, fig.height=4, out.extra='style="float:left"'}
# Lower and Upper East Side
# manhattan_les = c("10002", "10003", "10009")
# manhattan_ues = c("10021", "10028", "10044", "10128")
# zipZoom(response_per_zip, c(manhattan_les, manhattan_ues), 
#         "Response at Lower and Upper East Side", "Days")
```
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=4, fig.align='center', out.extra='style="float:middle"'}
# Upper West Side
manhattan_uwe = c("10025", "10026", "10027", "10030")
zipZoom(heat_response, manhattan_uwe, 
        "Zoom in Upper West Side", "Days")
```
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=4, fig.align='center', out.extra='style="float:right"'}
# Financial District 
manhattan_wall = c("10005", "10271", "10038", "10280", "10006", 
                    "10279", "10007", "10282", "10004")
zipZoom(heat_response, manhattan_wall, 
        "Zoom in Wall Street Area", "Days")
```

> #### Street Light Condition Complaints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
#DOT <- data[data$Agency=='DOT',]
#DOT_streetlight <- DOT[DOT$Complaint.Type=='Street Light Condition',]    # DOT  
# save(DOT_streetlight, file="DOT_streetlight.Rda")
# load("DOT_streetlight.Rda")

#zip_list_3 = unique(DOT_streetlight$Incident.Zip)    
#zip_list_3 = zip_list_3[is.na(zip_list_3) == FALSE]    #93 there is one empty entry
#zip_count_3 <- matrix(0, ncol=length(zip_list_3), nrow=1)
#colnames(zip_count_3) <- zip_list_3

#for (i in 1:length(zip_list_3)) {
#   temp = DOT_streetlight[DOT_streetlight$Incident.Zip == zip_list_3[i], ]
#   temp = temp[-which(is.na(temp$response)),]
#   zip_count_3[1, as.character(zip_list_3[i])] = round(mean(temp$response),2)
# } 
#rm(temp)
#streetlight_response = data.frame(region = colnames(zip_count_3), value =  #zip_count_3[,colnames(zip_count_3)])
#streetlight_response$region <- as.factor(streetlight_response$region)
#save(streetlight_response, file="streetlight_response.Rda")
load("streetlight_response.Rda")

# viewing a set of counties 
zip_choropleth(streetlight_response, county_zoom=nyc_fips,
            title="Average time for DOT to close the street light condition claims",
            legend="Days")
```

> #### Plumbing Complaints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
#HPD_plumbing <- HPD[HPD$Complaint.Type=='PLUMBING', ]
#zip_list_4 = unique(HPD_plumbing$Incident.Zip)
#zip_count_4 <- matrix(0, ncol=length(zip_list_4), nrow=1)
#colnames(zip_count_4) <- zip_list_4

#for (i in 1:length(zip_list_4)) {
#   temp = HPD_plumbing[HPD_plumbing$Incident.Zip == zip_list_4[i], ]
#   zip_count_4[1, as.character(zip_list_4[i])] = round(mean(temp$response),2)
# } 
#rm(temp)

#plumbing_response = data.frame(region = colnames(zip_count_4), value =  #zip_count_4[,colnames(zip_count_4)])
#plumbing_response$region <- as.factor(plumbing_response$region)
#save(plumbing_response, file="plumbing_response.Rda")
load("plumbing_response.Rda")
# viewing a set of counties 
zip_choropleth(plumbing_response, county_zoom=nyc_fips,
            title="Average time for HPD to close the plumbing claims",
            legend="Days")
```

> #### Waster System Complaints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
#DEP_water <- data[data$Complaint.Type=='Water System',] 
#zip_list_5 = unique(DEP_water$Incident.Zip)
#zip_list_5 = zip_list_5[is.na(zip_list_5) == FALSE]   # one empty zipcode entry
#zip_count_5 <- matrix(0, ncol=length(zip_list_5), nrow=1)
#colnames(zip_count_5) <- zip_list_5

#for (i in 1:length(zip_list_5)) {
#   temp = DEP_water[DEP_water$Incident.Zip == zip_list_5[i], ]
#   temp = temp[-which(is.na(temp$response)),]
#   zip_count_5[1, as.character(zip_list_5[i])] = round(mean(temp$response),2)
# } 
#rm(temp)

#watersys_response = data.frame(region = colnames(zip_count_5),
#                               value=zip_count_5[,colnames(zip_count_5)])

#watersys_response$region <- as.factor(watersys_response$region)
#save(watersys_response, file="watersys_response.Rda")
load("plumbing_response.Rda")
# viewing a set of counties 
zip_choropleth(plumbing_response, county_zoom=nyc_fips,
            title="Average time for DEP to close the waster system claims",
            legend="Days")
```

> #### Unsanitary Condition Complaints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
#HPD_unsanitary <- HPD[HPD$Complaint.Type=='UNSANITARY CONDITION', ]
#zip_list_6 = unique(HPD_unsanitary$Incident.Zip)
#zip_count_6 <- matrix(0, ncol=length(zip_list_6), nrow=1)
#colnames(zip_count_6) <- zip_list_6

#for (i in 1:length(zip_list_6)) {
#   temp = HPD_unsanitary[HPD_unsanitary$Incident.Zip == zip_list_6[i], ]
#   zip_count_6[1, as.character(zip_list_6[i])] = round(mean(temp$response),2)
# } 
#rm(temp)

#unsanitary_response = data.frame(region = colnames(zip_count_6), value =  zip_count_6[,colnames(zip_count_6)])
#unsanitary_response$region <- as.factor(unsanitary_response$region)
#save(unsanitary_response, file="unsanitary_response.Rda")
load("unsanitary_response.Rda")
# viewing a set of counties 
zip_choropleth(unsanitary_response, county_zoom=nyc_fips,
            title="Average time for HPD to close the unsanitary condition claims",
            legend="Days")
```
